version: "2.1"
dependencies: 
  - project: API4KBs/api4kbs
  - project: API4KBs/kmdp-bom
  - project: API4KBs/kmdp-models
    dependencies:
      - project: API4KBs/api4kbs
      - project: API4KBs/kmdp-bom

default:
  build-command:
    current: mvn clean install
    after:
      current: rm -rf ./*
      

build:
