name: Build_Develop

on:
 workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 

    steps:
          
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github 
        settings-path: "${{ github.workspace }}/.." 
        
        
# (meta) Maven configurable archetype plugin

    - name: Checkout Archetype plugin
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/maven-cfg-archetype-plugin
        ref: main
        
    - name: Deploy Archetype plugin
      run: mvn -B install -s "${{ github.workspace }}/../settings.xml" --no-transfer-progress
 
               
## kmdp-bom

    - name: Checkout BOM
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-bom
        ref: develop
        
    - name: Build BOM
      run: mvn -B deploy -Ppublic -Dmaven.source.includePom=true -s "${{ github.workspace }}/../settings.xml" --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

## api4kp

    - name: Checkout API4KP
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/api4kbs
        ref: develop
        
    - name: Deploy API4KP
      run: mvn -B deploy -Ppublic -Dmaven.source.includePom=true -s "${{ github.workspace }}/../settings.xml" --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      
    - name: Upload API4KP
      uses: actions/upload-artifact@v2
      with:
       path: '${{ github.workspace }}/**/target/*.jar'      
      
## kmdp-models (aka kmdp-impl)

    - name: Checkout Impl
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-models
        ref: develop
        
    - name: Build Impl
      run: mvn -B deploy -Ppublic -Dmaven.source.includePom=true -s "${{ github.workspace }}/../settings.xml" --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

    - name: Upload Impl
      uses: actions/upload-artifact@v2
      with:
       path: '${{ github.workspace }}/**/target/*.jar'
        
## kmdp-standards 

    - name: Checkout Standards
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-standard-models-impl
        ref: develop
        
    - name: Build Standards
      run: mvn -B deploy -Ppublic -Dmaven.source.includePom=true -s "${{ github.workspace }}/../settings.xml" --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

    - name: Upload Standards
      uses: actions/upload-artifact@v2
      with:
       path: '${{ github.workspace }}/**/target/*.jar'
     
## kmdp-openaapi-archetype 

    - name: Checkout Archetype
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-archetype
        ref: develop
        
    - name: Build Archetype
      run: mvn -B deploy -Ppublic -Dmaven.source.includePom=true -s "${{ github.workspace }}/../settings.xml" --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

    - name: Upload Archetype
      uses: actions/upload-artifact@v2
      with:
       path: '${{ github.workspace }}/**/target/*.jar'
  
## kmdp-api

    - name: Checkout API
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-api
        ref: develop
    
    - name: Code-gen API
      run: mvn -B clean install -Prefresh --no-transfer-progress
      
    - name: Build API
      run: mvn -B deploy -Ppublic -Dmaven.source.includePom=true -s "${{ github.workspace }}/../settings.xml" --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

    - name: Upload API
      uses: actions/upload-artifact@v2
      with:
       path: '${{ github.workspace }}/**/target/*.jar'  

       
## kmdp-knowledgebase

    - name: Checkout KnowledgeBase
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-knowledgebase-service
        ref: develop
    
    - name: Build KnowledgeBase
      run: mvn -B deploy -Ppublic -Dmaven.source.includePom=true -s "${{ github.workspace }}/../settings.xml" --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

    - name: Upload KnowledgeBase
      uses: actions/upload-artifact@v2
      with:
       path: '${{ github.workspace }}/**/target/*.jar'  
     

## kmdp-asset-repo

    - name: Checkout Asset Repo
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-asset-repository
        ref: develop
    
    - name: Build Asset Repo
      run: mvn -B deploy -Ppublic -Dmaven.source.includePom=true -s "${{ github.workspace }}/../settings.xml" --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

    - name: Upload Asset Repo
      uses: actions/upload-artifact@v2
      with:
       path: '${{ github.workspace }}/**/target/*.jar'
       
       
## kmdp-trisotech-asset-repository       

    - name: Checkout Trisotech KARS
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-trisotech-asset-repository
        ref: develop
    
    - name: Build TT KARS
      run: mvn -B deploy -Ppublic -Dmaven.source.includePom=true -s "${{ github.workspace }}/../settings.xml" --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

    - name: Upload TT KARS
      uses: actions/upload-artifact@v2
      with:
       path: '${{ github.workspace }}/**/target/*.jar'
  
