# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build Develop

on:
 workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file


    - name: Checkout API4KP
      uses: actions/checkout@v2
      with:
        repository: API4KBs/api4kbs
        ref: develop
        path: api4kbs

    - name: Checkout BOM
      uses: actions/checkout@v2
      with:
        repository: API4KBs/kmdp-bom
        ref: develop
        path: kmdp-bpm

    - name: Checkout Impl
      uses: actions/checkout@v2
      with:
        repository: API4KBs/kmdp-impl
        ref: develop
        path: kmdp-impl




    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2         


        
    - name: Build API4KP
      run: mvn -B package --file api4kbs/pom.xml    

    - name: Build BOM
      run: mvn -B package --file kmdp-bom/pom.xml

    - name: Build Impl
      run: mvn -B package --file kmdp-impl/pom.xml

   
