name: Build_Develop

on:
 workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Set up settings.xml
      uses: s4u/maven-settings-action@v2.5.0
      with:
       servers: '[{"id": "github", "username": "sotty", "password": "${{secrets.API4KP_TOKEN}}"}]'    
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace }} # location for the settings.xml file


#    - name: Set up Maven
#      uses: stCarolas/setup-maven@v4.2
#      with:
#        maven-version: 3.6.3


#    - name: Cache Maven packages
#     uses: actions/cache@v1
#      with:
#       path: ~/.m2
#       key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#       restore-keys: ${{ runner.os }}-m2         




    - name: Checkout API4KP
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/api4kbs
        ref: develop
        token: ${{secrets.API4KP_TOKEN}}
        
    - name: Deploy API4KP
      #run: mvn -B deploy --file api4kbs/pom.xml   
      run: mvn -B deploy -Ppublic 
      
    - name: Upload API4KP
      uses: actions/upload-artifact@v2
      with:
       path: target/**/*.jar      
      
    - name: Clean API4KP
      uses: AutoModality/action-clean@v1   
      


    - name: Checkout BOM
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-bom
        ref: develop
        token: ${{secrets.API4KP_TOKEN}}
        
    - name: Build BOM
      run: mvn -B deploy -Ppublic  
      
    - name: Clean BOM
      uses: AutoModality/action-clean@v1 




    - name: Checkout Impl
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-models
        ref: develop
        token: ${{secrets.API4KP_TOKEN}}
        
    - name: Build Impl
      run: mvn -B deploy -Ppublic   

    - name: Upload Impl
      uses: actions/upload-artifact@v2
      with:
       path: target/**/*.jar  

    - name: Clean Impl
      uses: AutoModality/action-clean@v1              
