name: Build_Develop

on:
 workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 

    steps:
          
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github 
        settings-path: "${{ github.workspace }}/.." 
        
        



    - name: Checkout BOM
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-bom
        ref: develop
        
    - name: Build BOM
      run: mvn -B deploy -Ppublic -Dmaven.source.includePom=true -s "${{ github.workspace }}/../settings.xml" --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      


    - name: Checkout API4KP
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/api4kbs
        ref: develop
        
    - name: Deploy API4KP
      run: mvn -B deploy -Ppublic -Dmaven.source.includePom=true -s "${{ github.workspace }}/../settings.xml" --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      
    - name: Upload API4KP
      uses: actions/upload-artifact@v2
      with:
       path: '${{ github.workspace }}/**/target/*.jar'      
      




    - name: Checkout Impl
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-models
        ref: develop
        
    - name: Build Impl
      run: mvn -B deploy -Ppublic -Dmaven.source.includePom=true -s "${{ github.workspace }}/../settings.xml" --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

    - name: Upload Impl
      uses: actions/upload-artifact@v2
      with:
       path: '${{ github.workspace }}/**/target/*.jar'
