name: Build_Develop

on:
 workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
          
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github 
        settings-path: ~/.m2 




    - name: Checkout API4KP
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/api4kbs
        ref: develop
        token: ${{secrets.API4KP_TOKEN}}
        
    - name: Deploy API4KP
      run: mvn -B deploy -Ppublic
      env:
        GITHUB_TOKEN: ${{ secrets.API4KP_TOKEN }}
        GITHUB_ACTOR: 'sotty'
      
    - name: Upload API4KP
      uses: actions/upload-artifact@v2
      with:
       path: '${{ github.workspace }}/**/target/*.jar'     
      
    - name: Clean API4KP
      uses: AutoModality/action-clean@v1   
      


    - name: Checkout BOM
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-bom
        ref: develop
        token: ${{secrets.API4KP_TOKEN}}
        
    - name: Build BOM
      run: mvn -B deploy -Ppublic 
      env:
        GITHUB_TOKEN: ${{ secrets.API4KP_TOKEN }}
        GITHUB_ACTOR: 'sotty'
        
    - name: Clean BOM
      uses: AutoModality/action-clean@v1 




    - name: Checkout Impl
      uses: actions/checkout@v2.3.4
      with:
        repository: API4KBs/kmdp-models
        ref: develop
        token: ${{secrets.API4KP_TOKEN}}
        
    - name: Build Impl
      run: mvn -B deploy -Ppublic
      env:
        GITHUB_TOKEN: ${{ secrets.API4KP_TOKEN }}    
        GITHUB_ACTOR: 'sotty'

    - name: Upload Impl
      uses: actions/upload-artifact@v2
      with:
       path: '${{ github.workspace }}/**/target/*.jar'

    - name: Clean Impl
      uses: AutoModality/action-clean@v1              
